[package]
name = "Pakistan"
version = "0.1.0"
authors = ["jamal-ud-din <user@example.comclear>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
